%% summarize simulation results
load('Record_alphaLB_MNAR.mat')
load('Record_alphaUB_MNAR.mat')
load('Record_alphaDel_MNAR.mat')

numIter = 25;
p_Missing_Candidate = [0.90, 0.95];
c_avg_Candidate = [0.5, 0.7, 0.9];
mu_abs_Candidate = [0.5, 1, 1.5];
sbar_Candidate = 0.25 * (2:6);

avg_alphaLB = mean(Record_alphaLB_MNAR, 1);
avg_alphaUB = mean(Record_alphaUB_MNAR, 1);
avg_alphaDel = mean(Record_alphaDel_MNAR, 1);

%% create plots for lower bounds
figure;
hold on;
% plot(sbar_Candidate, avg_alphaLB(1, :, 1, 1, 2), '-*',...
%     'Color', 'r',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaLB(1, :, 2, 1, 2), '-*',...
%     'Color', 'b',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaLB(1, :, 3, 1, 2), '-*',...
%     'Color', 'g',...
%     'LineWidth',2,...
%     'MarkerSize',10);

plot(sbar_Candidate, avg_alphaUB(1, :, 1, 3, 2), '-+',...
    'Color', 'r',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaUB(1, :, 2, 3, 2), '-+',...
    'Color', 'b',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaUB(1, :, 3, 3, 2), '-+',...
    'Color', 'g',...
    'LineWidth',2,...
    'MarkerSize',10);

plot(sbar_Candidate, alphaStar(3) * ones(1,5), '--')

xlabel('Bound for variance', 'FontWeight', 'bold', 'FontSize', 14);
ylabel('Bound for alpha', 'FontWeight', 'bold', 'FontSize', 14);
ax = gca;
ax.FontSize = 16;
hold off;



%% create plots for upper bounds
figure;
hold on;
plot(sbar_Candidate, avg_alphaLB(1, :, 1, 3, 2), '-*',...
    'Color', 'r',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaLB(1, :, 2, 3, 2), '-*',...
    'Color', 'b',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaLB(1, :, 3, 3, 2), '-*',...
    'Color', 'g',...
    'LineWidth',2,...
    'MarkerSize',10);

% plot(sbar_Candidate, avg_alphaUB(1, :, 1, 3, 1), '-+',...
%     'Color', 'r',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaUB(1, :, 2, 3, 1), '-+',...
%     'Color', 'b',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaUB(1, :, 3, 3, 1), '-+',...
%     'Color', 'g',...
%     'LineWidth',2,...
%     'MarkerSize',10);

plot(sbar_Candidate, alphaStar(3) * ones(1,5), '--')

xlabel('Lower bound for variance', 'FontWeight', 'bold', 'FontSize', 14);
ylabel('Lower bound for alpha', 'FontWeight', 'bold', 'FontSize', 14);
ax = gca;
ax.FontSize = 16;
hold off;



%% create plots for lower bounds (cavg = 0.7)
figure;
hold on;
% plot(sbar_Candidate, avg_alphaLB(1, :, 1, 1, 2), '-*',...
%     'Color', 'r',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaLB(1, :, 2, 1, 2), '-*',...
%     'Color', 'b',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaLB(1, :, 3, 1, 2), '-*',...
%     'Color', 'g',...
%     'LineWidth',2,...
%     'MarkerSize',10);

plot(sbar_Candidate, avg_alphaUB(1, :, 1, 2, 2), '-+',...
    'Color', 'r',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaUB(1, :, 2, 2, 2), '-+',...
    'Color', 'b',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaUB(1, :, 3, 2, 2), '-+',...
    'Color', 'g',...
    'LineWidth',2,...
    'MarkerSize',10);

plot(sbar_Candidate, alphaStar(2) * ones(1,5), '--')

xlabel('Bound for variance', 'FontWeight', 'bold', 'FontSize', 14);
ylabel('Upper bound for alpha', 'FontWeight', 'bold', 'FontSize', 14);
ax = gca;
ax.FontSize = 16;
hold off;



%% create plots for upper bounds
figure;
hold on;
plot(sbar_Candidate, avg_alphaLB(1, :, 1, 2, 2), '-*',...
    'Color', 'r',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaLB(1, :, 2, 2, 2), '-*',...
    'Color', 'b',...
    'LineWidth',2,...
    'MarkerSize',10);
plot(sbar_Candidate, avg_alphaLB(1, :, 3, 2, 2), '-*',...
    'Color', 'g',...
    'LineWidth',2,...
    'MarkerSize',10);

% plot(sbar_Candidate, avg_alphaUB(1, :, 1, 3, 1), '-+',...
%     'Color', 'r',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaUB(1, :, 2, 3, 1), '-+',...
%     'Color', 'b',...
%     'LineWidth',2,...
%     'MarkerSize',10);
% plot(sbar_Candidate, avg_alphaUB(1, :, 3, 3, 1), '-+',...
%     'Color', 'g',...
%     'LineWidth',2,...
%     'MarkerSize',10);

plot(sbar_Candidate, alphaStar(2) * ones(1,5), '--')

xlabel('Bound for variance', 'FontWeight', 'bold', 'FontSize', 14);
ylabel('Lower bound for alpha', 'FontWeight', 'bold', 'FontSize', 14);
ax = gca;
ax.FontSize = 16;
hold off;